# vim: nospell
#
# Basic template to test with GHC=[7.8, 7.10, 8.0], but also installs the
# relevant version of LLVM as (a very old version of) the CUDA toolkit (4.0).
# Caches the 'stack' build directory to speed subsequent compilations.
#
language: generic
dist: trusty
sudo: false

cache:
  directories:
    - $HOME/.stack
    - $HOME/llvm
    - .stack-work/downloaded
    - .stack-work/install

matrix:
  include:
    - env: GHC=7.8.4 CABAL=1.18 LLVM=3.5.2
      compiler: "GHC 7.8"
      addons: { apt: { sources: [ hvr-ghc, ubuntu-toolchain-r-test ], packages: [ nvidia-cuda-toolkit, g++-4.8, libgmp-dev, cabal-install-1.18, happy-1.19.5, alex-3.1.7 ] }}

    - env: GHC=7.10.3 CABAL=1.22 LLVM=3.5.2
      compiler: "GHC 7.10"
      addons: { apt: { sources: [ hvr-ghc, ubuntu-toolchain-r-test ], packages: [ nvidia-cuda-toolkit, g++-4.8, libgmp-dev, cabal-install-1.22, happy-1.19.5, alex-3.1.7 ] }}

    - env: GHC=8.0.1 CABAL=1.24 LLVM=3.8.0
      compiler: "GHC 8.0"
      addons: { apt: { sources: [ hvr-ghc, ubuntu-toolchain-r-test ], packages: [ nvidia-cuda-toolkit, g++-4.8, libgmp-dev, cabal-install-1.24, happy-1.19.5, alex-3.1.7 ] }}

    # - env: GHC=head CABAL=head LLVM=3.8.0
    #   compiler: "GHC HEAD"
    #   addons: { apt: { sources: [ hvr-ghc, ubuntu-toolchain-r-test ], packages: [ nvidia-cuda-toolkit, g++-4.8, ghc-head, cabal-install-head, happy-1.19.5, alex-3.1.7 ] }}

  allow_failures:
    - env: GHC=head CABAL=head LLVM=3.8.0

  fast_finish: true

before_install:
  - export PATH=/opt/cabal/$CABAL/bin:/opt/alex/3.1.7/bin:/opt/happy/1.19.5/bin:$HOME/.cabal/bin:$PATH
  - export UPGRADE_CABAL=1
  - source .travis/install-stack.sh
  - source .travis/install-llvm-trusty.sh

install:
  - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
  - cabal --version
  - stack --version
  - llc --version; true
  - opt --version; true
  - |
      if [ ${GHC} == head -o ! -e stack.yaml ]; then
        travis_retry cabal install --only-dependencies
      else
        travis_retry stack build --only-dependencies --no-terminal --no-haddock-deps --ghc-options="+RTS -A64M -n2M -RTS"
      fi

script:
  - |
      if [ ${GHC} == head -o ! -e stack.yaml ]; then
        travis_retry cabal install
        travis_retry cabal haddock
      else
        travis_retry stack build accelerate-llvm        --no-terminal --haddock --no-haddock-deps --ghc-options="+RTS -A648M -n2M -RTS"
        travis_retry stack build accelerate-llvm-native --no-terminal --haddock --no-haddock-deps --ghc-options="+RTS -A648M -n2M -RTS"
        travis_retry stack build accelerate-llvm-ptx    --no-terminal --haddock --no-haddock-deps --ghc-options="+RTS -A648M -n2M -RTS"
      fi

after_success:
  - source .travis/update-accelerate-buildbot.sh

