# vim: nospell
#
language: minimal
dist: trusty

cache:
  timeout: 600
  directories:
    - $HOME/.stack/snapshots
    - $HOME/.local/bin
    - .stack-work/install

before_cache:
  # - rm -rf $(stack path --local-install-root)/bin
  - rm -rf $(stack path --local-install-root)/doc

addons:
  apt:
    sources: &apt_sources
      - hvr-ghc
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty
    packages: &apt_packages
      - dpkg
      - gcc-8
      - g++-8
      - libgmp-dev
      - happy-1.19.5
      - alex-3.1.7

matrix:
  fast_finish: true
  include:
    - env: GHC=8.6.3 LLVM=7.0.1 CUDA=8.0.61-1
      compiler: "GHC 8.6"
      addons:
        apt:
          sources:
            - *apt_sources
            - llvm-toolchain-trusty-7
          packages:
            - *apt_packages
            - llvm-7-dev

    - env: GHC=8.4.3 LLVM=6.0.1 CUDA=8.0.61-1
      compiler: "GHC 8.4"
      addons:
        apt:
          sources:
            - *apt_sources
            - llvm-toolchain-trusty-6.0
          packages:
            - *apt_packages
            - llvm-6.0-dev

    - env: GHC=8.2.2 LLVM=5.0.2 CUDA=8.0.61-1
      compiler: "GHC 8.2"
      addons:
        apt:
          sources:
            - *apt_sources
            - llvm-toolchain-trusty-5.0
          packages:
            - *apt_packages
            - llvm-5.0-dev

    - env: GHC=8.0.2 LLVM=4.0.1 CUDA=8.0.61-1
      compiler: "GHC 8.0"
      addons:
        apt:
          sources:
            - *apt_sources
            - llvm-toolchain-trusty-4.0
          packages:
            - *apt_packages
            - llvm-4.0-dev

before_install:
  - export PATH=/opt/alex/3.1.7/bin:/opt/happy/1.19.5/bin:$PATH
  - export CUDA_INSTALL_EXTRA_LIBS=0  # cublas, cufft, etc.
  - source .travis/install-cuda-trusty.sh
  - source .travis/install-stack.sh

  # llvm-hs requires new g++
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 60 --slave /usr/bin/g++ g++ /usr/bin/g++-8

  # ghc-8.4+ require libffi7
  - echo "deb http://deb.debian.org/debian experimental main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key 0x7638D0442B90D010 0x8B48AD6246925553 0x04EE7237B7D453EC
  - sudo apt-get install debian-archive-keyring
  - sudo apt-get update
  - sudo apt-get install libffi7

  # ghc-8.6 builds a broken version of c2hs
  # - |
  #     if [ ${GHC%.*} == "8.6" -a ! -x "$(which c2hs)" ]; then
  #       travis_retry stack --stack-yaml=stack-8.4.yaml setup --no-terminal --no-system-ghc
  #       travis_retry stack --stack-yaml=stack-8.4.yaml install c2hs --fast --no-terminal
  #     fi

  # ghc-8.0/haddock crashes on dsImpSpecs
  - |
      case ${GHC%.*} in
        8.0) ;; # too slow ._.
        *  ) export HADDOCK="--haddock --no-haddock-deps" ;;
      esac

  # build environment
  - echo "$(stack exec ghc -- --version) [$(stack exec ghc -- --print-project-git-commit-id 2> /dev/null || echo '?')]"
  - stack --version
  - llc-${LLVM:0:3} --version; true
  - opt-${LLVM:0:3} --version; true

install:
  # how much do we have to do?
  - export FLAGS="--fast --jobs=2 --no-terminal --no-copy-bins --flag accelerate:nofib"
  - stack build $FLAGS --only-dependencies --test --dry-run

  # build dependencies
  - travis_retry                stack build accelerate $FLAGS --only-dependencies
  - travis_retry travis_wait 60 stack build accelerate $FLAGS
  - travis_retry                stack build            $FLAGS --only-dependencies --test

script:
  - true
  # - travis_retry stack build accelerate-llvm        $FLAGS $HADDOCK --test --no-run-tests
  # - travis_retry stack build accelerate-llvm-native $FLAGS $HADDOCK --test --no-run-tests
  # - travis_retry stack build accelerate-llvm-ptx    $FLAGS $HADDOCK --test --no-run-tests

  # # Run test suite(s)
  # # only use a single test thread due to limited memory on the travis boxes
  # - stack test accelerate-llvm-native $FLAGS --test-arguments='--hedgehog-tests=50 --hedgehog-shrinks=0 --timeout=30s --num-threads=1'

# after_success:
#   - source .travis/update-accelerate-buildbot.sh

